name: publish to ghcr

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '42 */6 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: ["25"]

    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: get upstream node version
        id: node_version
        run: |
          docker pull node:${{ matrix.node-version }}-trixie
          FULL_VERSION=$(docker run --rm node:${{ matrix.node-version }}-trixie node -v | cut -d 'v' -f 2)
          echo "Full version: $FULL_VERSION"
          MAJOR_MINOR=$(echo $FULL_VERSION | cut -d '.' -f 1,2)
          echo "Major.Minor: $MAJOR_MINOR"
          echo "full=$FULL_VERSION" >> $GITHUB_OUTPUT
          echo "minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT

      - name: login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=distroless-node
            org.opencontainers.image.description=distroless images for node.js current (non-LTS) versions
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.licenses=MIT
          tags: |
            type=raw,value=${{ matrix.node-version }}
            type=raw,value=${{ steps.node_version.outputs.full }}
            type=raw,value=${{ steps.node_version.outputs.minor }}
            type=raw,value=latest,enable=${{ matrix.node-version == '25' }}
            type=sha,priority=100

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
             NODE_VERSION=${{ matrix.node-version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=target,push=${{ github.event_name != 'pull_request' }},annotation-index.org.opencontainers.image.title=distroless-node,"annotation-index.org.opencontainers.image.description=distroless images for node.js current (non-LTS) versions",annotation-index.org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }},annotation-index.org.opencontainers.image.licenses=MIT
